---
title: "2020 Swisse BHT-Boost Sample"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C:/Users/LinQi/Desktop/Swisse/data monitoring")
library(readxl)
library(dplyr)
library(data.table)
library(knitr)

DATA<-read_xlsx(path = "77410286 data 1027.xlsx" )

```

## Category new user
```{r base, echo=FALSE}
options(digits = 0)
category_n<-DATA %>%
  filter(r00 == 3 & r01 ==3 & zjgroup == 1) 
category_n$O_F<-ifelse(category_n$s8 %in% c(11:19),1,2)
```

```{r function, include=FALSE}
MA<-function(Data,start,end,row,Base){
  setDT(Data)
  base<-Base
  total<-as.data.frame(apply(Data[,start:end], 2, sum, na.rm = T))
  
  gender<-matrix(nrow = row, ncol = 2)
  for(i in 1:2) {
    gender[,i]<-apply(Data[s1==i,][,start:end], 2, sum, na.rm = T)}
  
  age<-matrix(nrow = row, ncol = 3)
  a<-c(2:4)
  for(i in 1:3) {
    age[,i]<-apply(Data[age==a[i],][,start:end], 2, sum, na.rm = T)}
  
  city<-matrix(nrow = row, ncol = 3)
  for(i in 1:3) {
    city[,i]<-apply(Data[citytier==i,][,start:end], 2, sum, na.rm = T)}
  
  online_f<-matrix(nrow = row, ncol = 2)
  for(i in 1:2) {
    online_f[,i]<-apply(Data[O_F==i,][,start:end], 2, sum, na.rm = T)}
  
  output<-cbind(total, gender, age, city, online_f)
  output<-rbind(base, output)
  colnames(output)<-c("Total","Male", "Female", "20-29yo", "30-39yo","40-49yo","T1","T2","T3", "Offline", "Online")
  percent<-apply(output, 2, function(x) x[-1] / x[1])
  percent<-percent*100
  print(percent)
  
}
```


## Brand Choose Reason Swisse
```{r, include= F}
Swisse<-category_n %>%
  filter(a5x2<5 & b3x4 ==10)
T<-dim(Swisse)[1]
ba<-as.matrix(table(Swisse$s1))[1:2]
bb<-as.matrix(table(Swisse$age))[1:3]
bc<-as.matrix(table(Swisse$citytier))[1:3]
bd<-as.matrix(table(Swisse$O_F))[1:2]
Swisse_base<-c(T,ba, bb, bc, bd)

a<-which(variable.names(Swisse) == "D7x2_11_10")
b<-which(variable.names(Swisse) == "D7x2_54_10")
A<-MA(Data = Swisse,start =a, end = b,row = b-a+1,Base = Swisse_base)

rownames(A)<-c('品牌可信赖',	'品牌时尚',	'品牌专业',	'大品牌/知名品牌',	'来自澳洲的品牌',	'天然的/自然的品牌',	'产品见效快',	'产品功效有针对性，适合自己',	'产品有效成分含量高',	'产品包装和规格合适',	'产品有TAG认证',	'产品产地有保障',	'价格合适',	'有促销/推广活动',	'性价比高',	'店内有促销人员积极介绍',	'亲朋好友推荐',	'专家/医生推荐',	'社交媒体博主/网友推荐',	'电商平台/网站买家评价好',	'电商直播种草',	'在店内/货架陈列、展示醒目',	'很容易买到',	'购买时库存充足',	'广告比较多，受到影响')
```

```{r, echo=FALSE}
kable(A)
```

## Brand Choose Reason-Tangchen
```{r, include= F}
TC<-category_n %>%
  filter(a5x2<5 & b3x4==2)
T<-dim(TC)[1]
ba<-as.matrix(table(TC$s1))[1:2]
bb<-as.matrix(table(TC$age))[1:3]
bc<-as.matrix(table(TC$citytier))[1:3]
bd<-as.matrix(table(TC$O_F))[1:2]
TC_base<-c(T,ba, bb, bc, bd)
a<-which(variable.names(TC) == "D7x2_11_2")
b<-which(variable.names(TC) == "D7x2_54_2")
A<-MA(Data = TC, start =a, end = b,row = b-a+1,Base = TC_base)

rownames(A)<-c('品牌可信赖',	'品牌时尚',	'品牌专业',	'大品牌/知名品牌','来自澳洲的品牌',	'天然的/自然的品牌',	'产品见效快',	'产品功效有针对性，适合自己',	'产品有效成分含量高',	'产品包装和规格合适',	'蓝帽子认证',	'产品产地有保障',	'价格合适',	'有促销/推广活动',	'性价比高',	'店内有促销人员积极介绍',	'亲朋好友推荐',	'专家/医生推荐',	'社交媒体博主/网友推荐',	'电商平台/网站买家评价好',	'电商直播种草',	'在店内/货架陈列、展示醒目',	'很容易买到',	'购买时库存充足',	'广告比较多，受到影响')
```

```{r, echo=FALSE}
kable(A)
```


## Lost of user - Swisse
```{r, include= F}
Swisse_l<-DATA %>%
  filter(zjgroup == 2 & b3x0_10 == 1 & b3x1_10 != 1)
Swisse_l$O_F<-ifelse(Swisse_l$s8 %in% c(11:19),1,2)
Swisse_l$age[Swisse_l$age %in% c(5,6,7)]<-5

T<-dim(Swisse_l)[1]
ba<-as.matrix(table(Swisse_l$s1))[1:2]
bb<-as.matrix(table(Swisse_l$age))[1:3]
bc<-as.matrix(table(Swisse_l$citytier))[1:3]
bd<-as.matrix(table(Swisse_l$O_F))[1:2]
Swisse_l_base<-c(T,ba, bb, bc, bd)
```

### Category lost - Swisse
```{r, include=FALSE}
a<-which(variable.names(Swisse_l) == "D9x1_1_10")
b<-which(variable.names(Swisse_l) == "D9x1_43_10")
A<-MA(Data = Swisse_l, start =a, end = b,row = b-a+1,Base = Swisse_l_base)

rownames(A)<-c('复合维生素/多维（包含多种维生素）',	'维生素B',	'维生素C',	'维生素D',	'维生素E',	'钙',	'铁',	'锌',	'叶酸',	'蛋白粉',	'胶原蛋白',	'葡萄籽',	'美白丸/液',	'抗糖化丸/液',	'蔓越莓',	'月见草',	'圣洁莓',	'大豆异黄酮',	'左旋肉碱',	'叶绿素/大麦若叶',	'酵素', '护肝片（蓟/奶蓟草）',	'鱼油',	'卵磷脂',	'DHA',	'辅酶Q10',	'牛初乳',	'蜂皇浆',	'蜂胶',	'玛咖',	'人参/西洋参',	'益生菌',	'膳食纤维/果蔬纤维',	'氨基葡萄糖',	'软骨素',	'关节灵',	'芹菜籽',	'褪黑素',	'睡眠片',	'血糖宁/血糖片',	'叶黄素',	'蓝莓')
```
```{r, echo=FALSE}
kable(A)
```

### Lose to Brand - Swisse
```{r, include=FALSE}
a<-which(variable.names(Swisse_l) == "D9x2_1_10")
b<-which(variable.names(Swisse_l) == "D9x2_99_10")
A<-MA(Data = Swisse_l, start =a, end = b,row = b-a+1,Base = Swisse_l_base)

rownames(A)<-c('Amway',	'汤臣倍健',	'无限极',	'善存',	'钙尔奇',	'Herbalife',	'盖中盖',	'修正',	'养生堂',	'Swisse',	'Blackmores',	'GNC',	'Natures Bounty',	'Healthy Care',	'Life Space',	'Move Free',	'Bioisland',	'Childlife',	'Culturelle',	'合生元',	'Hech',	'Pola',	'Doppelherz', '其他', '不食用品类')
```
```{r, echo=FALSE}
kable(A)
```

### Lost to Category
```{r, include=FALSE}
a<-which(variable.names(Swisse_l) == "D9x3_1_10")
b<-which(variable.names(Swisse_l) == "D9x3_43_10")
A<-MA(Data = Swisse_l, start =a, end = b,row = b-a+1,Base = Swisse_l_base)

rownames(A)<-c('复合维生素/多维（包含多种维生素）',	'维生素B',	'维生素C',	'维生素D',	'维生素E',	'钙',	'铁',	'锌',	'叶酸',	'蛋白粉',	'胶原蛋白',	'葡萄籽',	'美白丸/液',	'抗糖化丸/液',	'蔓越莓',	'月见草',	'圣洁莓',	'大豆异黄酮',	'左旋肉碱',	'叶绿素/大麦若叶',	'酵素', '护肝片（蓟/奶蓟草）',	'鱼油',	'卵磷脂',	'DHA',	'辅酶Q10',	'牛初乳',	'蜂皇浆',	'蜂胶',	'玛咖',	'人参/西洋参',	'益生菌',	'膳食纤维/果蔬纤维',	'氨基葡萄糖',	'软骨素',	'关节灵',	'芹菜籽',	'褪黑素',	'睡眠片',	'血糖宁/血糖片',	'叶黄素',	'蓝莓')
```
```{r, echo=FALSE}
kable(A)
```

### Lost to Category - To Tangchen
```{r, include=FALSE}
S_t_T<-filter(Swisse_l) %>%
  filter(D9x2_2_10 == 1)

T<-dim(S_t_T)[1]
ba<-as.matrix(table(S_t_T$s1))[1:2]
bb<-as.matrix(table(S_t_T$age))[1:3]
bc<-as.matrix(table(S_t_T$citytier))[1:3]
bd<-as.matrix(table(S_t_T$O_F))[1:2]
S_t_T_base<-c(T,ba, bb, bc, bd)

a<-which(variable.names(S_t_T) == "D9x3_1_10")
b<-which(variable.names(S_t_T) == "D9x3_43_10")
A<-MA(Data = S_t_T, start =a, end = b,row = b-a+1,Base = S_t_T_base)

rownames(A)<-c('复合维生素/多维（包含多种维生素）',	'维生素B',	'维生素C',	'维生素D',	'维生素E',	'钙',	'铁',	'锌',	'叶酸',	'蛋白粉',	'胶原蛋白',	'葡萄籽',	'美白丸/液',	'抗糖化丸/液',	'蔓越莓',	'月见草',	'圣洁莓',	'大豆异黄酮',	'左旋肉碱',	'叶绿素/大麦若叶',	'酵素', '护肝片（蓟/奶蓟草）',	'鱼油',	'卵磷脂',	'DHA',	'辅酶Q10',	'牛初乳',	'蜂皇浆',	'蜂胶',	'玛咖',	'人参/西洋参',	'益生菌',	'膳食纤维/果蔬纤维',	'氨基葡萄糖',	'软骨素',	'关节灵',	'芹菜籽',	'褪黑素',	'睡眠片',	'血糖宁/血糖片',	'叶黄素',	'蓝莓')
```
```{r, echo=FALSE}
kable(A)
```

### Lost reason - Swisse
```{r, include=FALSE}
a<-which(variable.names(Swisse_l) == "D9x4_11_10")
b<-which(variable.names(Swisse_l) == "D9x4_53_10")
A<-MA(Data = Swisse_l, start =a, end = b,row = b-a+1,Base = Swisse_l_base)

rownames(A)<-c('感觉总体效果不好',	'有依赖性',	'感觉有副作用/副作用大',	'口味不如其他品牌',	'感觉不如其他品牌见效快',	'感觉不如其他品牌有针对性，更适合自己',	'其他品牌有效成分含量高',	'其他品牌产品包装和规格合适',	'其他品牌产地更有保障',	'当时是促销/特价才购买的',	'其他品牌效果相当，价格更便宜',	'亲朋好友推荐其他品牌',	'专家/医生建议食用其他品牌',	'网上的达人/博主推荐食用其他品牌',	'看到其它产品的广告，宣传其他产品效果更好',	'平时购买保健品的渠道买不到',	'在电商渠道看不到广告/宣传',	'代购没有卖')
```
```{r, echo=FALSE}
kable(A)
```

